version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - '8055:8000'
  #   depends_on:
  #     - postgres
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydb
